simple_motor:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    pos_position:
      joint1:
        type: position_controllers/JointPositionController
        joint: joint1
      joint2:
        type: position_controllers/JointPositionController
        joint: joint2
    eff_position:
      joint1:
        type: effort_controllers/JointPositionController
        joint: joint1
        pid: {p: 0.0, i: 0.0, d: 0.0}
    vel_position:
      joint1:
        type: velocity_controllers/JointPositionController
        joint: joint1
        pid: {p: 3.0, i: 0.1, d: 0.4}