simple_motor:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      joint1:
        type: position_controllers/JointPositionController
        joint: joint1